export enum OrderStatus {
	PENDING = 'PENDING',
	PAID = 'PAID',
	SHIPPED = 'SHIPPED',
	DELIVERED = 'DELIVERED',
	CANCELLED = 'CANCELLED',
	REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
	// Cards
	CARD = 'CARD',
	CREDIT_CARD = 'CREDIT_CARD',
	DEBIT_CARD = 'DEBIT_CARD',

	// Digital Wallets
	KAKAOPAY = 'KAKAOPAY',
	NAVERPAY = 'NAVERPAY',
	PAYCO = 'PAYCO',
	TOSS = 'TOSS',
	SAMSUNG_PAY = 'SAMSUNG_PAY',
	APPLE_PAY = 'APPLE_PAY',
	GOOGLE_PAY = 'GOOGLE_PAY',

	// Bank Transfer
	BANK_TRANSFER = 'BANK_TRANSFER',
	VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT',

	// Other
	CASH = 'CASH',
	COD = 'COD', // Cash on Delivery
	POINTS = 'POINTS', // Loyalty points
	GIFT_CARD = 'GIFT_CARD',
}

export enum PaymentStatus {
	PENDING = 'PENDING',
	PROCESSING = 'PROCESSING',
	AUTHORIZED = 'AUTHORIZED',
	CAPTURED = 'CAPTURED',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	CANCELLED = 'CANCELLED',
	REFUNDED = 'REFUNDED',
	PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
	EXPIRED = 'EXPIRED',
}

export enum ShippingMethod {
	STANDARD = 'STANDARD',
	EXPRESS = 'EXPRESS',
	OVERNIGHT = 'OVERNIGHT',
	PICKUP = 'PICKUP',
	SAME_DAY = 'SAME_DAY',
	INTERNATIONAL = 'INTERNATIONAL',
}

export enum RefundReason {
	CHANGED_MIND = 'CHANGED_MIND',
	DEFECTIVE_PRODUCT = 'DEFECTIVE_PRODUCT',
	WRONG_ITEM = 'WRONG_ITEM',
	NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
	DAMAGED_IN_SHIPPING = 'DAMAGED_IN_SHIPPING',
	LATE_DELIVERY = 'LATE_DELIVERY',
	DUPLICATE_ORDER = 'DUPLICATE_ORDER',
	ALLERGIC_REACTION = 'ALLERGIC_REACTION',
	BETTER_PRICE_FOUND = 'BETTER_PRICE_FOUND',
	OTHER = 'OTHER',
}

export enum OrderItemStatus {
	PENDING = 'PENDING',
	CONFIRMED = 'CONFIRMED',
	PREPARING = 'PREPARING',
	SHIPPED = 'SHIPPED',
	DELIVERED = 'DELIVERED',
	CANCELLED = 'CANCELLED',
	RETURNED = 'RETURNED',
	REFUNDED = 'REFUNDED',
}

export enum CancellationReason {
	CUSTOMER_REQUEST = 'CUSTOMER_REQUEST',
	OUT_OF_STOCK = 'OUT_OF_STOCK',
	PAYMENT_FAILED = 'PAYMENT_FAILED',
	FRAUD_SUSPECTED = 'FRAUD_SUSPECTED',
	ADDRESS_ISSUE = 'ADDRESS_ISSUE',
	DUPLICATE_ORDER = 'DUPLICATE_ORDER',
	SELLER_UNAVAILABLE = 'SELLER_UNAVAILABLE',
	OTHER = 'OTHER',
}
