// dummyProducts.ts
import { Product, MeLiked } from './types/product/product';
import { ProductStatus, ProductType } from './enums/product.enum';

export const dummyProducts: Product[] = [
	{
		_id: '1',
		productCategory: 'Skincare',
		productStock: 50,
		productType: ProductType.SKINCARE, // example enum
		productStatus: ProductStatus.ACTIVE, // example enum
		productTitle: 'K-Beauty Hydrating Serum',
		productPrice: 29.99,
		productViews: 120,
		productLikes: 15,
		productComments: 5,
		productRank: 1,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Hydrating serum with vitamin C for glowing skin.',
		memberId: 'user1',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '1', myFavorite: true }],
	},
	{
		_id: '2',
		productCategory: 'Makeup',
		productStock: 30,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'BB Cream SPF50',
		productPrice: 19.99,
		productViews: 80,
		productLikes: 10,
		productComments: 2,
		productRank: 2,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Lightweight BB cream for a natural look with sun protection.',
		memberId: 'user2',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '2', myFavorite: false }],
	},
	{
		_id: '3',
		productCategory: 'Makeup',
		productStock: 100,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Long-Lasting Lip Tint',
		productPrice: 12.99,
		productViews: 200,
		productLikes: 30,
		productComments: 8,
		productRank: 3,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Long-lasting Korean lip tint for vibrant color.',
		memberId: 'user3',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '3', myFavorite: false }],
	},
	{
		_id: '3',
		productCategory: 'Makeup',
		productStock: 100,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Long-Lasting Lip Tint',
		productPrice: 12.99,
		productViews: 200,
		productLikes: 30,
		productComments: 8,
		productRank: 3,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Long-lasting Korean lip tint for vibrant color.',
		memberId: 'user3',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '3', myFavorite: false }],
	},
	{
		_id: '3',
		productCategory: 'Makeup',
		productStock: 100,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Long-Lasting Lip Tint',
		productPrice: 12.99,
		productViews: 200,
		productLikes: 30,
		productComments: 8,
		productRank: 3,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Long-lasting Korean lip tint for vibrant color.',
		memberId: 'user3',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '3', myFavorite: false }],
	},
	{
		_id: '3',
		productCategory: 'Makeup',
		productStock: 100,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Long-Lasting Lip Tint',
		productPrice: 12.99,
		productViews: 200,
		productLikes: 30,
		productComments: 8,
		productRank: 3,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Long-lasting Korean lip tint for vibrant color.',
		memberId: 'user3',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '3', myFavorite: false }],
	},
	{
		_id: '3',
		productCategory: 'Makeup',
		productStock: 100,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Long-Lasting Lip Tint',
		productPrice: 12.99,
		productViews: 200,
		productLikes: 30,
		productComments: 8,
		productRank: 3,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Long-lasting Korean lip tint for vibrant color.',
		memberId: 'user3',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '3', myFavorite: false }],
	},
];
