// dummyProducts.ts
import { Product } from './types/product/product';
import { ProductStatus, ProductType, SkinType } from './enums/product.enum';

export const dummyProducts: Product[] = [
	{
		_id: '1',
		productCategory: 'Skincare',
		productStock: 50,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'K-Beauty Hydrating Serum',
		productPrice: 29.99,
		productViews: 120,
		productLikes: 15,
		productComments: 5,
		productRank: 1,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Hydrating serum with vitamin C for glowing skin.',
		memberId: 'user1',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '1', myFavorite: true }],
		skinType: [SkinType.DRY, SkinType.SENSITIVE],
	},
	{
		_id: '2',
		productCategory: 'Makeup',
		productStock: 30,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'BB Cream SPF50',
		productPrice: 19.99,
		productViews: 80,
		productLikes: 10,
		productComments: 2,
		productRank: 2,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Lightweight BB cream for a natural look with sun protection.',
		memberId: 'user2',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '2', myFavorite: false }],
		skinType: [SkinType.OILY, SkinType.COMBINATION],
	},
	{
		_id: '3',
		productCategory: 'Makeup',
		productStock: 100,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Long-Lasting Lip Tint',
		productPrice: 12.99,
		productViews: 200,
		productLikes: 30,
		productComments: 8,
		productRank: 3,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Long-lasting Korean lip tint for vibrant color.',
		memberId: 'user3',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '3', myFavorite: false }],
		skinType: [SkinType.NORMAL, SkinType.OILY],
	},
	{
		_id: '4',
		productCategory: 'Skincare',
		productStock: 60,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Centella Calming Toner',
		productPrice: 22.99,
		productViews: 150,
		productLikes: 25,
		productComments: 6,
		productRank: 4,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Centella asiatica toner that soothes redness and irritation.',
		memberId: 'user1',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '4', myFavorite: false }],
		skinType: [SkinType.SENSITIVE, SkinType.NORMAL],
	},
	{
		_id: '5',
		productCategory: 'Skincare',
		productStock: 45,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Niacinamide Pore Essence',
		productPrice: 18.99,
		productViews: 175,
		productLikes: 20,
		productComments: 4,
		productRank: 5,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Niacinamide essence to minimize pores and control shine.',
		memberId: 'user2',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '5', myFavorite: false }],
		skinType: [SkinType.OILY, SkinType.COMBINATION],
	},
	{
		_id: '6',
		productCategory: 'Skincare',
		productStock: 70,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'Rich Barrier Cream',
		productPrice: 34.99,
		productViews: 95,
		productLikes: 18,
		productComments: 3,
		productRank: 6,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Deeply nourishing cream that restores the skin barrier overnight.',
		memberId: 'user3',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '6', myFavorite: false }],
		skinType: [SkinType.DRY, SkinType.NORMAL],
	},
	{
		_id: '7',
		productCategory: 'Skincare',
		productStock: 55,
		productType: ProductType.SKINCARE,
		productStatus: ProductStatus.ACTIVE,
		productTitle: 'AHA/BHA Exfoliating Pad',
		productPrice: 25.99,
		productViews: 130,
		productLikes: 22,
		productComments: 7,
		productRank: 7,
		productImages: ['/img/products/serum1.jpg'],
		productDesc: 'Gentle exfoliating pads with AHA and BHA for smoother skin.',
		memberId: 'user2',
		createdAt: new Date(),
		updatedAt: new Date(),
		meLiked: [{ memberId: 'user1', likeRefId: '7', myFavorite: false }],
		skinType: [SkinType.COMBINATION, SkinType.SENSITIVE],
	},
];
